#CHANGE THE PATHS
ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, true,
                   false, false, false,
                   true, true, true]
    
    imu0: /imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  true, true, true]

    use_control: false
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link